const PHONETICS = {
  "a bunch of": "/ʌ bˈʌntʃ ˈʌv/",
  "above all": "/ʌbˈʌv ˈɔl/",
  "abstract": "/æbstrˈækt/",
  "accent": "/ʌksˈɛnt/",
  "acid": "/ˈæsʌd/",
  "adaptation": "/ˌædʌpˈteɪʃʌn/",
  "advertisement": "/ædvˈɝtʌzmʌnt/",
  "advisor (also adviser)": "/ædvˈaɪzɝ/",
  "aerospace": "/ˈɛroʊspˌeɪs/",
  "airline": "/ˈɛrlˌaɪn/",
  "aisha": "/ˈaɪʃʌ/",
  "alongside": "/ʌlˈɔŋsaɪd/",
  "ambition": "/æmbˈɪʃʌn/",
  "ambitious": "/æmbˈɪʃʌs/",
  "ambulance": "/ˈæmbjʌlʌns/",
  "angle": "/ˈæŋɡʌl/",
  "ankle": "/ˈæŋkʌl/",
  "anticipate": "/æntˈɪsʌpˌeɪt/",
  "antique": "/æntˈik/",
  "anyhow": "/ˈɛnihˌaʊ/",
  "applicant": "/ˈæplɪkʌnt/",
  "arise": "/ɝˈaɪz/",
  "as far as i am concerned": "/ˈæz fˈɑr ˈæz ˈaɪ ˈæm kʌnsˈɝnd/",
  "as far as i know": "/ˈæz fˈɑr ˈæz ˈaɪ nˈoʊ/",
  "assistant": "/ʌsˈɪstʌnt/",
  "association": "/ʌsˌoʊsˈieɪʃʌn/",
  "astonish": "/ʌstˈɑnɪʃ/",
  "astronomer": "/ʌstrˈɑnʌmɝ/",
  "astronomy": "/ʌstrˈɑnʌmi/",
  "aviation": "/ˌeɪvˈieɪʃʌn/",
  "awesome": "/ˈɑsʌm/",
  "bacon": "/bˈeɪkʌn/",
  "bath": "/bˈæθ/",
  "bathtub": "/bˈæθtʌb/",
  "bay": "/bˈeɪ/",
  "bean curd (also tofu)": "/bˈin kˈɝd/",
  "behave": "/bɪhˈeɪv/",
  "belt": "/bˈɛlt/",
  "besides": "/bɪsˈaɪdz/",
  "blame": "/blˈeɪm/",
  "bleed": "/blˈid/",
  "bleeding": "/blˈidɪŋ/",
  "blister": "/blˈɪstɝ/",
  "bold": "/bˈoʊld/",
  "boom": "/bˈum/",
  "border": "/bˈɔrdɝ/",
  "bound": "/bˈaʊnd/",
  "brand": "/brˈænd/",
  "break out": "/brˈeɪk ˈaʊt/",
  "breath": "/brˈɛθ/",
  "brilliant": "/brˈɪljʌnt/",
  "budget": "/bˈʌdʒɪt/",
  "bun": "/bˈʌn/",
  "bunch": "/bˈʌntʃ/",
  "butchart gardens": "/bˈʊtʃɝt ɡˈɑrdʌnz/",
  "cabbage": "/kˈæbʌdʒ/",
  "cafeteria": "/kˌæfʌˈtɪriʌ/",
  "calorie": "/kˈælɝi/",
  "cambridge": "/kˈeɪmbrɪdʒ/",
  "canteen": "/kæntˈin/",
  "carpet": "/kˈɑrpʌt/",
  "cast": "/kˈæst/",
  "category": "/kˈætʌɡˌɔri/",
  "cell": "/sˈɛl/",
  "chef": "/ʃˈɛf/",
  "chew": "/tʃˈu/",
  "choke": "/tʃˈoʊk/",
  "cholera": "/kˈɑlɝʌ/",
  "cite": "/sˈaɪt/",
  "cobblestone": "/kˈɑbʌlstˌoʊn/",
  "coherent": "/koʊhˈɪrʌnt/",
  "come down with": "/kˈʌm dˈaʊn wˈɪð/",
  "comfort": "/kˈʌmfɝt/",
  "comfort zone": "/kˈʌmfɝt zˈoʊn/",
  "competence": "/kˈɑmpʌtɪns/",
  "competent": "/kˈɑmpʌtɪnt/",
  "complex": "/kˈɑmplɛks/",
  "concept": "/kˈɑnsɛpt/",
  "concrete": "/kʌnkrˈit/",
  "consist": "/kʌnsˈɪst/",
  "consist of": "/kʌnsˈɪst ˈʌv/",
  "consistent": "/kʌnsˈɪstʌnt/",
  "consume": "/kʌnsˈum/",
  "contradictory": "/kˌɑntrʌˈdɪktɝi/",
  "contrary": "/kˈɑntrɛri/",
  "contrary to": "/kˈɑntrɛri tˈu/",
  "cooperate": "/koʊˈɑpɝˌeɪt/",
  "cost an arm and a leg": "/kˈɑst ˈæn ˈɑrm ʌnd ʌ lˈɛɡ/",
  "craft": "/krˈæft/",
  "cuisine": "/kwɪzˈin/",
  "culture shock": "/kˈʌltʃɝ ʃˈɑk/",
  "curtain": "/kˈɝtʌn/",
  "dairy": "/dˈɛri/",
  "decrease": "/dɪkrˈis/",
  "defend": "/dɪfˈɛnd/",
  "dehydration": "/dˌihaɪdˈreɪʃʌn/",
  "delay": "/dɪlˈeɪ/",
  "deny": "/dɪnˈaɪ/",
  "departure": "/dɪpˈɑrtʃɝ/",
  "depress": "/dɪprˈɛs/",
  "depressed": "/dɪprˈɛst/",
  "desperate": "/dˈɛsprɪt/",
  "dessert": "/dɪzˈɝt/",
  "diarrhoea": "/dˌaɪˈɝiʌ/",
  "dim sum": "/dˈɪm sˈʌm/",
  "diner": "/dˈaɪnɝ/",
  "dough": "/dˈoʊ/",
  "dramatic": "/drʌmˈætɪk/",
  "drill": "/drˈɪl/",
  "drown": "/drˈaʊn/",
  "duration": "/dˈʊreɪʃʌn/",
  "dusk": "/dˈʌsk/",
  "ease": "/ˈiz/",
  "edition": "/ʌdˈɪʃʌn/",
  "edmonton": "/ˈɛdmʌntʌn/",
  "elderly": "/ˈɛldɝli/",
  "electric": "/ɪlˈɛktrɪk/",
  "electric shock": "/ɪlˈɛktrɪk ʃˈɑk/",
  "elegant": "/ˈɛlʌɡʌnt/",
  "engage": "/ɛnɡˈeɪdʒ/",
  "engage in": "/ɛnɡˈeɪdʒ ɪn/",
  "envoy": "/ˈɛnvɔɪ/",
  "epidemiology": "/ˌɛpʌdˌɛˈmiɑlʌdʒi/",
  "exceptional": "/ɪksˈɛpʃʌnʌl/",
  "expectation": "/ˌɛkspɛkˈteɪʃʌn/",
  "expense": "/ɪkspˈɛns/",
  "expose": "/ɪkspˈoʊz/",
  "exposure": "/ɪkspˈoʊʒɝ/",
  "fabric": "/fˈæbrɪk/",
  "face up/down": "/fˈeɪs ˈʌp dˈaʊn/",
  "fault": "/fˈɔlt/",
  "feel at home": "/fˈil ˈæt hˈoʊm/",
  "fellow": "/fˈɛloʊ/",
  "fibre (especially us fiber)": "/fˈaɪbɝ/",
  "fig": "/fˈɪɡ/",
  "finding": "/fˈaɪndɪŋ/",
  "firm": "/fˈɝm/",
  "fist": "/fˈɪst/",
  "framework": "/frˈeɪmwˌɝk/",
  "fred hoyle": "/frˈɛd hˈɔɪl/",
  "freeze": "/frˈiz/",
  "freezing": "/frˈizɪŋ/",
  "freezing cold": "/frˈizɪŋ kˈoʊld/",
  "frost": "/frˈɔst/",
  "frustrated": "/frˈʌstrˌeɪtʌd/",
  "fundamental": "/fˌʌndʌˈmɛntʌl/",
  "furthermore": "/fˈɝðɝmˌɔr/",
  "gain": "/ɡˈeɪn/",
  "garlic": "/ɡˈɑrlɪk/",
  "generally speaking": "/dʒˈɛnɝʌli spˈikɪŋ/",
  "germ": "/dʒˈɝm/",
  "get involved in": "/ɡˈɛt ˌɪnˈvɑlvd ɪn/",
  "gifted": "/ɡˈɪftʌd/",
  "goat": "/ɡˈoʊt/",
  "grab": "/ɡrˈæb/",
  "grasp": "/ɡrˈæsp/",
  "grizzly bear": "/ɡrˈɪzli bˈɛr/",
  "haggis": "/hˈæɡʌs/",
  "halifax": "/hˈælɪfˌæks/",
  "ham": "/hˈæm/",
  "handle": "/hˈændʌl/",
  "harbour (especially us harbor)": "/hˈɑrbɝ/",
  "highlight": "/hˈaɪlˌaɪt/",
  "homesickness": "/hˈoʊmsˌɪknʌs/",
  "household": "/hˈaʊshˌoʊld/",
  "ideal": "/aɪdˈil/",
  "idiom": "/ˈɪdiʌm/",
  "in charge of": "/ɪn tʃˈɑrdʒ ˈʌv/",
  "in summary": "/ɪn sˈʌmɝi/",
  "infect": "/ˌɪnˈfɛkt/",
  "infection": "/ˌɪnˈfɛkʃʌn/",
  "ingredient": "/ˌɪnɡˈridiʌnt/",
  "initial": "/ˌɪˈnɪʃʌl/",
  "initiative": "/ˌɪˈnɪʃʌtɪv/",
  "insight": "/ˈɪnsˌaɪt/",
  "interrupt": "/ˌɪntˈɝʌpt/",
  "intervention": "/ˌɪntɝˈvɛnʃʌn/",
  "involve": "/ˌɪnˈvɑlv/",
  "jasper": "/dʒˈæspɝ/",
  "jean-philippe": "/dʒˈin-fɪlˈipeɪ/",
  "jet": "/dʒˈɛt/",
  "junk": "/dʒˈʌŋk/",
  "junk food (also junk)": "/dʒˈʌŋk fˈud/",
  "lake huron": "/lˈeɪk hjˈurˌɑn/",
  "lake louise": "/lˈeɪk luˈiz/",
  "lamb": "/lˈæm/",
  "lamb kebab": "/lˈæm kʌbˈɑb/",
  "layer": "/lˈeɪɝ/",
  "leadership": "/lˈidɝʃˌɪp/",
  "leaflet": "/lˈiflʌt/",
  "link": "/lˈɪŋk/",
  "literally": "/lˈɪtɝʌli/",
  "logical": "/lˈɑdʒɪkʌl/",
  "loose": "/lˈus/",
  "madam": "/mˈædʌm/",
  "mall (also shopping mall)": "/mˈɔl/",
  "massive": "/mˈæsɪv/",
  "mature": "/mʌtʃˈʊr/",
  "mechanic": "/mʌkˈænɪk/",
  "mechanical": "/mʌkˈænɪkʌl/",
  "messenger": "/mˈɛsʌndʒɝ/",
  "microscope": "/mˈaɪkrʌskˌoʊp/",
  "millimetre": "/mˈɪlʌmˌitɝ/",
  "minimum": "/mˈɪnʌmʌm/",
  "minor": "/mˈaɪnɝ/",
  "missile": "/mˈɪsʌl/",
  "mist": "/mˈɪst/",
  "misty": "/mˈɪsti/",
  "moderation": "/mˌɑdˈɝeɪʃʌn/",
  "modest": "/mˈɑdʌst/",
  "montreal": "/mˌʌntrˈiɔl/",
  "mosquito": "/mʌskˈitoʊ/",
  "motion": "/mˈoʊʃʌn/",
  "motivate": "/mˈoʊtʌvˌeɪt/",
  "motivated": "/mˈoʊtʌvˌeɪtʌd/",
  "motivation": "/mˌoʊtʌˈveɪʃʌn/",
  "multiple": "/mˈʌltʌpʌl/",
  "needle": "/nˈidʌl/",
  "nerve": "/nˈɝv/",
  "niagara falls": "/naɪˈæɡrʌ fˈɔlz/",
  "non-newtonian fluid": "/nˈɑn-nutˈoʊniʌn flˈuʌd/",
  "nova scotia": "/nˈoʊvʌ skˈoʊʃʌ/",
  "obstruction": "/ʌbstrˈʌkʃʌn/",
  "olive": "/ˈɑlʌv/",
  "once and for all": "/wˈʌns ʌnd fˈɔr ˈɔl/",
  "onion": "/ˈʌnjʌn/",
  "ontario": "/ɑntˈɛrioʊ/",
  "operator": "/ˈɑpɝˌeɪtɝ/",
  "optimistic": "/ˌɑptʌˈmɪstɪk/",
  "organ": "/ˈɔrɡʌn/",
  "outcome": "/ˈaʊtkˌʌm/",
  "outlook": "/ˈaʊtlˌʊk/",
  "outstanding": "/ˌaʊtsˈtændɪŋ/",
  "overall": "/ˈoʊvɝˌɔl/",
  "overwhelming": "/ˌoʊvɝˈwɛlmɪŋ/",
  "owe": "/ˈoʊ/",
  "panic": "/pˈænɪk/",
  "paramedic": "/pˌɛrʌˈmɛdɪk/",
  "participate": "/pɑrtˈɪsʌpˌeɪt/",
  "participate in": "/pɑrtˈɪsʌpˌeɪt ɪn/",
  "participation": "/pɑrtˌɪsʌˈpeɪʃʌn/",
  "patriotic": "/pˌeɪtrˈiɑtɪk/",
  "peak": "/pˈik/",
  "pearl": "/pˈɝl/",
  "pepper": "/pˈɛpɝ/",
  "perspective": "/pɝspˈɛktɪv/",
  "photographer": "/fʌtˈɑɡrʌfɝ/",
  "plasma": "/plˈæzmʌ/",
  "pleasant": "/plˈɛzʌnt/",
  "pork": "/pˈɔrk/",
  "pour": "/pˈɔr/",
  "practical": "/prˈæktʌkʌl/",
  "prairie": "/prˈɛri/",
  "presentation": "/prˌɛzʌnˈteɪʃʌn/",
  "prior": "/prˈaɪɝ/",
  "prior to": "/prˈaɪɝ tˈu/",
  "proceed": "/prʌsˈid/",
  "proof": "/prˈuf/",
  "protein": "/prˈoʊtˌin/",
  "pump": "/pˈʌmp/",
  "pure": "/pjˈʊr/",
  "qualification": "/kwˌɑlʌfʌˈkeɪʃʌn/",
  "qualify": "/kwˈɑlʌfˌaɪ/",
  "quantity": "/kwˈɑntʌti/",
  "quarry": "/kwˈɔri/",
  "quebec city": "/kwʌbˈɛk sˈɪti/",
  "queen victoria": "/kwˈin vɪktˈɔriʌ/",
  "radiation": "/rˌeɪdˈieɪʃʌn/",
  "rainbow": "/rˈeɪnbˌoʊ/",
  "raw": "/rˈɑ/",
  "ray": "/rˈeɪ/",
  "reasonable": "/rˈizʌnʌbʌl/",
  "recall": "/rˈikˌɔl/",
  "recipe": "/rˈɛsʌpi/",
  "red braised pork": "/rˈɛd brˈeɪzd pˈɔrk/",
  "regardless": "/rʌɡˈɑrdlʌs/",
  "regardless of": "/rʌɡˈɑrdlʌs ˈʌv/",
  "rome": "/rˈoʊm/",
  "sausage": "/sˈɔsʌdʒ/",
  "scenery": "/sˈinɝi/",
  "scream": "/skrˈim/",
  "sense of touch": "/sˈɛns ˈʌv tˈʌtʃ/",
  "setting": "/sˈɛtɪŋ/",
  "severe": "/sʌvˈɪr/",
  "shadow": "/ʃˈædˌoʊ/",
  "shift": "/ʃˈɪft/",
  "shore": "/ʃˈɔr/",
  "side with": "/sˈaɪd wˈɪð/",
  "sincerely": "/sɪnsˈɪrli/",
  "slap": "/slˈæp/",
  "slice": "/slˈaɪs/",
  "slice... off": "/slˈaɪs ˈɔf/",
  "slip": "/slˈɪp/",
  "solid": "/sˈɑlʌd/",
  "somewhat": "/sˈʌmwʌt/",
  "speak up": "/spˈik ˈʌp/",
  "spectacular": "/spɛktˈækjʌlɝ/",
  "sprain": "/sprˈeɪn/",
  "st andrews": "/strˈit ˈændrˌuz/",
  "st lawrence river": "/strˈit lˈɔrʌns rˈɪvɝ/",
  "stable": "/stˈeɪbʌl/",
  "statistic": "/stʌtˈɪstɪk/",
  "steady": "/stˈɛdi/",
  "steak": "/stˈeɪk/",
  "steel": "/stˈil/",
  "stephen hawking": "/stˈivʌn hˈɔkɪŋ/",
  "strengthen": "/strˈɛŋθʌn/",
  "stuff": "/stˈʌf/",
  "subscribe": "/sʌbskrˈaɪb/",
  "subscribe to": "/sʌbskrˈaɪb tˈu/",
  "substantial": "/sʌbstˈænʃʌl/",
  "surrounding": "/sɝˈaʊndɪŋ/",
  "surroundings": "/sɝˈaʊndɪŋz/",
  "suspect": "/sʌspˈɛkt/",
  "swallow": "/swˈɑloʊ/",
  "swell": "/swˈɛl/",
  "swollen": "/swˈoʊlʌn/",
  "take sb’s breath away": "/tˈeɪk brˈɛθ ʌwˈeɪ/",
  "technique": "/tɛknˈik/",
  "temper": "/tˈɛmpɝ/",
  "thanks to": "/θˈæŋks tˈu/",
  "the belt and road initiative": "/ðʌ bˈɛlt ʌnd rˈoʊd ˌɪˈnɪʃʌtɪv/",
  "the big bang theory": "/ðʌ bˈɪɡ bˈæŋ θˈɪri/",
  "the jet propulsion laboratory": "/ðʌ dʒˈɛt prʌpˈʌlʃʌn lˈæbrʌtˌɔri/",
  "theoretical framework": "/θˌiˈɝɛtɪkʌl frˈeɪmwˌɝk/",
  "thinking": "/θˈɪŋkɪŋ/",
  "throat": "/θrˈoʊt/",
  "thunder": "/θˈʌndɝ/",
  "tight": "/tˈaɪt/",
  "tightly": "/tˈaɪtli/",
  "toast": "/tˈoʊst/",
  "toronto": "/tɝˈɑntoʊ/",
  "toxin": "/tˈɑksʌn/",
  "trace": "/trˈeɪs/",
  "transform": "/trænsfˈɔrm/",
  "tremendous": "/trʌmˈɛndʌs/",
  "trick": "/trˈɪk/",
  "tutor": "/tˈutɝ/",
  "underneath": "/ˌʌndɝˈniθ/",
  "urgent": "/ˈɝdʒʌnt/",
  "vaccine": "/vˌækˈsin/",
  "vancouver": "/vænkˈuvɝ/",
  "vegetarian": "/vˌɛdʒʌˈtɛrˌiʌn/",
  "victim": "/vˈɪktʌm/",
  "vinegar": "/vˈɪnʌɡɝ/",
  "virus": "/vˈaɪrʌs/",
  "vital sign": "/vˈaɪtʌl sˈaɪn/",
  "vitamin": "/vˈaɪtʌmʌn/",
  "vivid": "/vˈɪvʌd/",
  "ward": "/wˈɔrd/",
  "water pump": "/wˈɔtɝ pˈʌmp/",
  "winnipeg": "/wˈɪnɪpʌɡ/",
  "wrap": "/rˈæp/",
  "zone": "/zˈoʊn/"
};

